name: DrakesRankup
version: '${project.version}'
main: com.drakescraft.rankup.DrakesRankupPlugin
api-version: '1.21'
author: DrakesCraft-Labs
description: Sistema oficial de 50 Rangos Anime/Shonen, Transformaciones Saiyajin, Modo Angel y Sumidero de Economía
softdepend: [Vault, LuckPerms, PlaceholderAPI]
commands:
  rankup:
    description: Abre la interfaz de Rankup, asciende de rango o gestiona pruebas.
    aliases: [ranks, rangos, subirrango, rank, subir, habilidades, skills, abilities]
  angel:
    description: Modo Staff de Deidad Angelical (Invulnerabilidad y Ultra Instinto Infinito).
    aliases: [zenosama, zeno, daishinkan]
    permission: drakesrankup.staff
  transform:
    description: Abre la interfaz interactiva para escoger transformaciones y poderes anime.
    aliases: [transformaciones, ki, poderes, transformacion]
  rebirth:
    description: Sistema de Renacimiento Supremo (Rebirth) hasta un máximo de 50 niveles.
    aliases: [renacer, renacimiento, rebirths]
